server:
  port: 8083
spring:
  application:
    name: Prices
  data:
    mongodb:
      uri: mongodb://localhost:27017/prices
integration:
  seller:
    url: http://localhost:8080
feign:
  connectionTimeout: 60000
  readTimeout: 60000
integra-sellers:
  seller:
    broadcast: "integra-sellers.seller.broadcast"